### ISSUE TITLE
All Armor is Helmets

### ISSUE THREAD

**Issue by BioMasterZap** [Paulem79/SimpleOres-fabric#1]
I'm a fan of the original mod and saw this port so I gave it a test and noticed some issues. This is for Fabric 1.20.4 with Simple Ores v1.0.0 and Bucketlib 3.2.1.3.

It appears that all of the armor have the same values (e.g. all pieces of Onyx are 5 Armor) and can only be equipped in the Head slot.

Also for Onyx Ore spawning, it seems to pop up in some strange places, like a single ore inside some Soul Sand or in Basalt. I saw the ore generation is data pack driven, but not quite sure how "nether_carver_replaceables" works or if there is a way to get it to only replace netherrack.

Final thing I wanted to bring up/ask: are there plans for configs to modify and/or disable stuff? It seems data packs can configure the ores, but not sure if there would be an easy way to "turn off" an ore completely (maybe set spawning to 0 0?). But one of the defining things of Simple Ores was the ability to tweak all the values for the different tiers, so it would be nice to see some ways to do that for the fabric version. Also, it would be nice to see Fusion again, but a config is probably already a big enough undertaking.

**Comment by Paulem79** [comment]
Hello, thanks for your report

It's strange that all armors have the same value and can only be used on head (wtf ?) I'll urgely take a look at that
I can make onyx ore only appear in netherrack, and I'll do that after what you said, the original mod uses "nether_carver_replaceables", so I used it (maybe that wasn't a good idea ahaha)

I plan a config already for some values in the mod, but I can surely make it more editable, I'll take a look at that too :D
I take a look to implement Fusion too, but I don't know if it'll be easy, I might have to change a lot of code, and that would be a good thing because 1.20.4 and before's code is a bit, hum, rushed 😅

**Comment by Paulem79** [comment]
I'M DUMB
that's what I can say

**Comment by Paulem79** [comment]
That was just a line to edit lmao

**Comment by Paulem79** [comment]
Okay, I'll do everything in one time, and then I'll update on Modrinth :D

**Comment by Paulem79** [comment]
Okay, I finished everything for 1.20.4, let's do that for the other versions too :D

**Comment by Paulem79** [comment]
Oh and, ores are datapack-driven :'( (so not editable in the config)
I don't think it's possible to register ores in another way than by them being a "datapack"

**Comment by BioMasterZap** [comment]
Using a data pack for Ores seems easy enough, even if I'm sure some would be more comfortable with a config. But do you know of a good way to disable an ore using a data pack? Maybe turning the Size or Count to 0 would do it?

**Comment by Paulem79** [comment]
Yeah, just turning a value to 0

**Comment by Paulem79** [comment]
just 1.19.4 remaining

**Comment by Paulem79** [comment]
finally, let's publish that on Modrinth and Curseforge

**Comment by Paulem79** [comment]
Perfect ! It's now on those platforms ! Thanks for your report and your help <3
I close this as completed ;)
